# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Api.Calls do
  @moduledoc """
  API calls for all endpoints tagged `Calls`.
  """

  alias PlacetelAPI.Connection
  import PlacetelAPI.RequestBuilder

  @doc """
  Delete a call
  Delete a call by its ID

  ### Parameters

  - `connection` (PlacetelAPI.Connection): Connection to server
  - `id` (integer()): Call ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_calls_id(Tesla.Env.client(), integer(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def delete_calls_id(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/calls/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false}
    ])
  end

  @doc """
  Fetch all incoming calls
  Provides a list of all calls on a specific day (`date`) or today.

  ### Parameters

  - `connection` (PlacetelAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:"filter[date]"` (Date.t): YYYY-MM-DD, defaults to today.
    - `:"filter[from_number]"` (String.t): 
    - `:"filter[to_number]"` (String.t): 
    - `:"filter[type]"` (String.t): 
    - `:order` (String.t): 
    - `:page` (integer()): Page of results to fetch.
    - `:per_page` (integer()): Number of results to return per page.

  ### Returns

  - `{:ok, [%Call{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_calls(Tesla.Env.client(), keyword()) ::
          {:ok, list(PlacetelAPI.Model.Call.t())} | {:error, Tesla.Env.t()}
  def get_calls(connection, opts \\ []) do
    optional_params = %{
      :"filter[date]" => :query,
      :"filter[from_number]" => :query,
      :"filter[to_number]" => :query,
      :"filter[type]" => :query,
      :order => :query,
      :page => :query,
      :per_page => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/calls")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, [%PlacetelAPI.Model.Call{}]}
    ])
  end

  @doc """
  Retrieve a call
  Fetches a call by its ID

  ### Parameters

  - `connection` (PlacetelAPI.Connection): Connection to server
  - `id` (integer()): Call ID
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, PlacetelAPI.Model.Call.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_calls_id(Tesla.Env.client(), integer(), keyword()) ::
          {:ok, PlacetelAPI.Model.Call.t()} | {:error, Tesla.Env.t()}
  def get_calls_id(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/calls/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %PlacetelAPI.Model.Call{}}
    ])
  end

  @doc """
  Initate a call
  Initates a call

  ### Parameters

  - `connection` (PlacetelAPI.Connection): Connection to server
  - `calls` (PostCalls): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec post_calls(Tesla.Env.client(), PlacetelAPI.Model.PostCalls.t(), keyword()) ::
          {:ok, nil} | {:error, Tesla.Env.t()}
  def post_calls(connection, calls, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/calls")
      |> add_param(:body, :body, calls)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, false}
    ])
  end
end
