# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Api.RoutingPlanObjects do
  @moduledoc """
  API calls for all endpoints tagged `RoutingPlanObjects`.
  """

  alias PlacetelAPI.Connection
  import PlacetelAPI.RequestBuilder

  @doc """
  Get a routing plans objects
  Get objects for routing plan

  ### Parameters

  - `connection` (PlacetelAPI.Connection): Connection to server
  - `id` (String.t): ID of a routing plan
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, [%RoutingObject{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_routing_plans_id_routings(Tesla.Env.client(), String.t(), keyword()) ::
          {:ok, list(PlacetelAPI.Model.RoutingObject.t())} | {:error, Tesla.Env.t()}
  def get_routing_plans_id_routings(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/routing_plans/#{id}/routings")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, [%PlacetelAPI.Model.RoutingObject{}]}
    ])
  end
end
