# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.CallCenterQueue do
  @moduledoc """
  CallCenterQueue model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :num_loops,
    :priority,
    :description,
    :mail_notification,
    :ringing_time,
    :max_iterations,
    :play_prompt,
    :prompt,
    :play_prompt_waiting,
    :prompt_waiting,
    :play_prompt_end,
    :prompt_end,
    :play_mailbox,
    :prompt_mailbox,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :num_loops => String.t() | nil,
          :priority => String.t() | nil,
          :description => String.t() | nil,
          :mail_notification => String.t() | nil,
          :ringing_time => String.t() | nil,
          :max_iterations => String.t() | nil,
          :play_prompt => String.t() | nil,
          :prompt => PlacetelAPI.Model.Prompt.t() | nil,
          :play_prompt_waiting => String.t() | nil,
          :prompt_waiting => PlacetelAPI.Model.Prompt.t() | nil,
          :play_prompt_end => String.t() | nil,
          :prompt_end => PlacetelAPI.Model.Prompt.t() | nil,
          :play_mailbox => String.t() | nil,
          :prompt_mailbox => PlacetelAPI.Model.Prompt.t() | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.CallCenterQueue do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:prompt, :struct, PlacetelAPI.Model.Prompt, options)
    |> deserialize(:prompt_waiting, :struct, PlacetelAPI.Model.Prompt, options)
    |> deserialize(:prompt_end, :struct, PlacetelAPI.Model.Prompt, options)
    |> deserialize(:prompt_mailbox, :struct, PlacetelAPI.Model.Prompt, options)
  end
end
