# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.CallDetailRecord do
  @moduledoc """
  CallDetailRecord model
  """

  @derive [Poison.Encoder]
  defstruct [
    :amount,
    :description,
    :from,
    :to,
    :length,
    :answer_uri,
    :received_at
  ]

  @type t :: %__MODULE__{
          :amount => float() | nil,
          :description => String.t() | nil,
          :from => String.t() | nil,
          :to => String.t() | nil,
          :length => integer() | nil,
          :answer_uri => String.t() | nil,
          :received_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.CallDetailRecord do
  def decode(value, _options) do
    value
  end
end
