# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.CallCenterAgent do
  @moduledoc """
  CallCenterAgent model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :description,
    :extension_sip,
    :extension_pstn,
    :extension_type,
    :agent_type,
    :status,
    :priority,
    :last_call_at,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :extension_sip => String.t() | nil,
          :extension_pstn => String.t() | nil,
          :extension_type => String.t() | nil,
          :agent_type => String.t() | nil,
          :status => String.t() | nil,
          :priority => integer() | nil,
          :last_call_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.CallCenterAgent do
  def decode(value, _options) do
    value
  end
end
