# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.CallCenterCall do
  @moduledoc """
  CallCenterCall model
  """

  @derive [Poison.Encoder]
  defstruct [
    :call_type,
    :call_status,
    :answer_status,
    :started_at,
    :left_queue_at,
    :ended_at,
    :last_updated_at,
    :iteration,
    :from,
    :to,
    :queue_name,
    :agent_name
  ]

  @type t :: %__MODULE__{
          :call_type => String.t() | nil,
          :call_status => String.t() | nil,
          :answer_status => String.t() | nil,
          :started_at => DateTime.t() | nil,
          :left_queue_at => DateTime.t() | nil,
          :ended_at => DateTime.t() | nil,
          :last_updated_at => DateTime.t() | nil,
          :iteration => String.t() | nil,
          :from => String.t() | nil,
          :to => String.t() | nil,
          :queue_name => String.t() | nil,
          :agent_name => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.CallCenterCall do
  def decode(value, _options) do
    value
  end
end
