# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.CustomConfiguration do
  @moduledoc """
  CustomConfiguration model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :key,
    :value,
    :attributes
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :key => String.t() | nil,
          :value => String.t() | nil,
          :attributes => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.CustomConfiguration do
  def decode(value, _options) do
    value
  end
end
