# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Device do
  @moduledoc """
  Device model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :display_name,
    :manufacturer,
    :lines,
    :blf_keys,
    :expansion_keys,
    :max_expansion_modules,
    :dect_lines,
    :multicell,
    :encryptable
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :display_name => String.t() | nil,
          :manufacturer => String.t() | nil,
          :lines => String.t() | nil,
          :blf_keys => String.t() | nil,
          :expansion_keys => String.t() | nil,
          :max_expansion_modules => String.t() | nil,
          :dect_lines => String.t() | nil,
          :multicell => String.t() | nil,
          :encryptable => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Device do
  def decode(value, _options) do
    value
  end
end
