# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Fax do
  @moduledoc """
  Fax model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :type,
    :from_number,
    :to_number,
    :pages,
    :retries,
    :status,
    :status_info,
    :email,
    :header,
    :duration,
    :file,
    :report,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :type => String.t() | nil,
          :from_number => String.t() | nil,
          :to_number => String.t() | nil,
          :pages => integer() | nil,
          :retries => integer() | nil,
          :status => String.t() | nil,
          :status_info => String.t() | nil,
          :email => String.t() | nil,
          :header => String.t() | nil,
          :duration => integer() | nil,
          :file => String.t() | nil,
          :report => String.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Fax do
  def decode(value, _options) do
    value
  end
end
