# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Group do
  @moduledoc """
  Group model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :description,
    :type,
    :members,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :type => String.t() | nil,
          :members => [PlacetelAPI.Model.SipUser.t()] | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Group do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:members, :list, PlacetelAPI.Model.SipUser, options)
  end
end
