# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Key do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :label,
    :value,
    :position,
    :extended
  ]

  @type t :: %__MODULE__{
          :type => String.t() | nil,
          :label => String.t() | nil,
          :value => String.t() | nil,
          :position => String.t() | nil,
          :extended => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Key do
  def decode(value, _options) do
    value
  end
end
