# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Line do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :sipuid,
    :position
  ]

  @type t :: %__MODULE__{
          :sipuid => String.t() | nil,
          :position => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Line do
  def decode(value, _options) do
    value
  end
end
