# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Me do
  @moduledoc """
  Me model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :email,
    :company,
    :primary_sip_user_id,
    :platform,
    :rights_numbers,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :email => String.t() | nil,
          :company => String.t() | nil,
          :primary_sip_user_id => integer() | nil,
          :platform => String.t() | nil,
          :rights_numbers => [String.t()] | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Me do
  def decode(value, _options) do
    value
  end
end
