# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Number do
  @moduledoc """
  Number model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :routing_id,
    :prefix,
    :numonly,
    :number,
    :activated,
    :test_number,
    :name,
    :description,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :routing_id => String.t() | nil,
          :prefix => String.t() | nil,
          :numonly => String.t() | nil,
          :number => String.t() | nil,
          :activated => boolean() | nil,
          :test_number => boolean() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Number do
  def decode(value, _options) do
    value
  end
end
