# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Permission do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :blocks,
    :enabled
  ]

  @type t :: %__MODULE__{
          :blocks => [String.t()] | nil,
          :enabled => boolean() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Permission do
  def decode(value, _options) do
    value
  end
end
