# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostSms do
  @moduledoc """
  Send SMS
  """

  @derive [Poison.Encoder]
  defstruct [
    :recipient,
    :message
  ]

  @type t :: %__MODULE__{
          :recipient => String.t(),
          :message => String.t()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostSms do
  def decode(value, _options) do
    value
  end
end
