# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostCtiMacStartConference do
  @moduledoc """
  Start conference
  """

  @derive [Poison.Encoder]
  defstruct [
    :line,
    :call_id
  ]

  @type t :: %__MODULE__{
          :line => integer(),
          :call_id => integer()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostCtiMacStartConference do
  def decode(value, _options) do
    value
  end
end
