# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostCtiMacBlindTransfer do
  @moduledoc """
  Blind transfer
  """

  @derive [Poison.Encoder]
  defstruct [
    :line,
    :call_id,
    :number
  ]

  @type t :: %__MODULE__{
          :line => integer(),
          :call_id => integer(),
          :number => String.t()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostCtiMacBlindTransfer do
  def decode(value, _options) do
    value
  end
end
