# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostRoutings do
  @moduledoc """
  Create a routing object
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :forward,
    :group,
    :ivr,
    :queue,
    :api,
    :mailbox,
    :notification,
    :time_settings,
    :custom_callerid,
    :music_on_hold,
    :notify_external_api
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :forward => PlacetelAPI.Model.PutRoutingsForward.t() | nil,
          :group => PlacetelAPI.Model.PutRoutingsGroup.t() | nil,
          :ivr => PlacetelAPI.Model.PutRoutingsIvr.t() | nil,
          :queue => PlacetelAPI.Model.PutRoutingsQueue.t() | nil,
          :api => PlacetelAPI.Model.PutRoutingsApi.t() | nil,
          :mailbox => PlacetelAPI.Model.PutRoutingsMailbox.t() | nil,
          :notification => PlacetelAPI.Model.PutRoutingsNotification.t() | nil,
          :time_settings => PlacetelAPI.Model.PostRoutingsTimeSettings.t() | nil,
          :custom_callerid => PlacetelAPI.Model.PutRoutingsCustomCallerid.t() | nil,
          :music_on_hold => boolean() | nil,
          :notify_external_api => boolean() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostRoutings do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:forward, :struct, PlacetelAPI.Model.PutRoutingsForward, options)
    |> deserialize(:group, :struct, PlacetelAPI.Model.PutRoutingsGroup, options)
    |> deserialize(:ivr, :struct, PlacetelAPI.Model.PutRoutingsIvr, options)
    |> deserialize(:queue, :struct, PlacetelAPI.Model.PutRoutingsQueue, options)
    |> deserialize(:api, :struct, PlacetelAPI.Model.PutRoutingsApi, options)
    |> deserialize(:mailbox, :struct, PlacetelAPI.Model.PutRoutingsMailbox, options)
    |> deserialize(:notification, :struct, PlacetelAPI.Model.PutRoutingsNotification, options)
    |> deserialize(:time_settings, :struct, PlacetelAPI.Model.PostRoutingsTimeSettings, options)
    |> deserialize(
      :custom_callerid,
      :struct,
      PlacetelAPI.Model.PutRoutingsCustomCallerid,
      options
    )
  end
end
