# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostSipUsersIdShortCodes do
  @moduledoc """
  Create short code
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :code,
    :number,
    :group_id,
    :description
  ]

  @type t :: %__MODULE__{
          :action => String.t(),
          :code => String.t(),
          :number => String.t() | nil,
          :group_id => integer() | nil,
          :description => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostSipUsersIdShortCodes do
  def decode(value, _options) do
    value
  end
end
