# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostFaxes do
  @moduledoc """
  Create outbound fax
  """

  @derive [Poison.Encoder]
  defstruct [
    :from_number,
    :to_number,
    :email,
    :file,
    :header
  ]

  @type t :: %__MODULE__{
          :from_number => String.t(),
          :to_number => String.t(),
          :email => String.t(),
          :file => String.t(),
          :header => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostFaxes do
  def decode(value, _options) do
    value
  end
end
