# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostCtiMacDialDigit do
  @moduledoc """
  Dial digit
  """

  @derive [Poison.Encoder]
  defstruct [
    :line,
    :call_id,
    :digit
  ]

  @type t :: %__MODULE__{
          :line => integer(),
          :call_id => integer(),
          :digit => String.t()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostCtiMacDialDigit do
  def decode(value, _options) do
    value
  end
end
