# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostCtiMacSendDtmfDigits do
  @moduledoc """
  Send DTMF Digits
  """

  @derive [Poison.Encoder]
  defstruct [
    :digits
  ]

  @type t :: %__MODULE__{
          :digits => String.t()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostCtiMacSendDtmfDigits do
  def decode(value, _options) do
    value
  end
end
