# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PostNumbersNumberIdProfiles do
  @moduledoc """
  Creates a new profile for a number
  """

  @derive [Poison.Encoder]
  defstruct [
    :name
  ]

  @type t :: %__MODULE__{
          :name => String.t()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PostNumbersNumberIdProfiles do
  def decode(value, _options) do
    value
  end
end
