# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Profile do
  @moduledoc """
  Profile model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :number_id,
    :active
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :number_id => integer() | nil,
          :active => boolean() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Profile do
  def decode(value, _options) do
    value
  end
end
