# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Prompt do
  @moduledoc """
  Prompt model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :description,
    :text,
    :file,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :text => String.t() | nil,
          :file => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Prompt do
  def decode(value, _options) do
    value
  end
end
