# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutCallCenterAgents do
  @moduledoc """
  Update an agent
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :priority,
    :description,
    :status
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :priority => integer() | nil,
          :description => String.t() | nil,
          :status => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutCallCenterAgents do
  def decode(value, _options) do
    value
  end
end
