# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutProvisioningsIdCustomConfigurationsConfigurations do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :key,
    :value,
    :attributes
  ]

  @type t :: %__MODULE__{
          :key => String.t(),
          :value => String.t(),
          :attributes => String.t() | nil
        }
end

defimpl Poison.Decoder,
  for: PlacetelAPI.Model.PutProvisioningsIdCustomConfigurationsConfigurations do
  def decode(value, _options) do
    value
  end
end
