# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutRoutingsGroup do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :group_ringing_time,
    :backup_behaviour,
    :backup_routing_object_id
  ]

  @type t :: %__MODULE__{
          :id => String.t(),
          :group_ringing_time => String.t() | nil,
          :backup_behaviour => String.t() | nil,
          :backup_routing_object_id => integer() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutRoutingsGroup do
  def decode(value, _options) do
    value
  end
end
