# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutRoutingsNotification do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :salutation,
    :email,
    :type,
    :receiver
  ]

  @type t :: %__MODULE__{
          :salutation => String.t() | nil,
          :email => String.t() | nil,
          :type => String.t() | nil,
          :receiver => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutRoutingsNotification do
  def decode(value, _options) do
    value
  end
end
