# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutProvisionings do
  @moduledoc """
  Update a phone provisionings
  """

  @derive [Poison.Encoder]
  defstruct [
    :webuser_id,
    :name,
    :codec,
    :call_waiting,
    :encryption,
    :locale,
    :lines,
    :keys
  ]

  @type t :: %__MODULE__{
          :webuser_id => integer() | nil,
          :name => String.t() | nil,
          :codec => String.t() | nil,
          :call_waiting => boolean() | nil,
          :encryption => String.t() | nil,
          :locale => String.t() | nil,
          :lines => [String.t()] | nil,
          :keys => [PlacetelAPI.Model.PutProvisioningsKeysInner.t()] | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutProvisionings do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:keys, :list, PlacetelAPI.Model.PutProvisioningsKeysInner, options)
  end
end
