# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutCti do
  @moduledoc """
  Set config params
  """

  @derive [Poison.Encoder]
  defstruct [
    :params
  ]

  @type t :: %__MODULE__{
          :params => map()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutCti do
  def decode(value, _options) do
    value
  end
end
