# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutRoutingsApi do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :max_retries,
    :backup_routing_plan_id,
    :prompt_id
  ]

  @type t :: %__MODULE__{
          :max_retries => integer(),
          :backup_routing_plan_id => integer() | nil,
          :prompt_id => integer() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutRoutingsApi do
  def decode(value, _options) do
    value
  end
end
