# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutRoutingsCustomCallerid do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :callerid_enabled,
    :callerid_name,
    :callerid_number
  ]

  @type t :: %__MODULE__{
          :callerid_enabled => boolean() | nil,
          :callerid_name => String.t() | nil,
          :callerid_number => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutRoutingsCustomCallerid do
  def decode(value, _options) do
    value
  end
end
