# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutRoutingsMailbox do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :greeting_id,
    :mp3
  ]

  @type t :: %__MODULE__{
          :active => boolean() | nil,
          :greeting_id => integer() | nil,
          :mp3 => boolean() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutRoutingsMailbox do
  def decode(value, _options) do
    value
  end
end
