# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutProvisioningsIdCustomConfigurations do
  @moduledoc """
  Update or create a phone provisionings custom configuration key
  """

  @derive [Poison.Encoder]
  defstruct [
    :configurations
  ]

  @type t :: %__MODULE__{
          :configurations =>
            PlacetelAPI.Model.PutProvisioningsIdCustomConfigurationsConfigurations.t()
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutProvisioningsIdCustomConfigurations do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :configurations,
      :struct,
      PlacetelAPI.Model.PutProvisioningsIdCustomConfigurationsConfigurations,
      options
    )
  end
end
