# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutRoutingsIvr do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :prompt_id,
    :item_1_id,
    :item_2_id,
    :item_3_id,
    :item_4_id,
    :item_5_id,
    :item_6_id,
    :item_7_id,
    :item_8_id,
    :item_9_id,
    :catchall_routing_object_id
  ]

  @type t :: %__MODULE__{
          :prompt_id => integer() | nil,
          :item_1_id => integer() | nil,
          :item_2_id => integer() | nil,
          :item_3_id => integer() | nil,
          :item_4_id => integer() | nil,
          :item_5_id => integer() | nil,
          :item_6_id => integer() | nil,
          :item_7_id => integer() | nil,
          :item_8_id => integer() | nil,
          :item_9_id => integer() | nil,
          :catchall_routing_object_id => integer() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutRoutingsIvr do
  def decode(value, _options) do
    value
  end
end
