# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutUsersPermissions do
  @moduledoc """
  Configure advanced permission of this user
  """

  @derive [Poison.Encoder]
  defstruct [
    :enabled,
    :blocks
  ]

  @type t :: %__MODULE__{
          :enabled => boolean() | nil,
          :blocks => [String.t()]
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutUsersPermissions do
  def decode(value, _options) do
    value
  end
end
