# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutRoutingsForward do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :destinations,
    :behaviour,
    :prompt_id
  ]

  @type t :: %__MODULE__{
          :destinations => [PlacetelAPI.Model.PutRoutingsForwardDestinationsInner.t()],
          :behaviour => String.t() | nil,
          :prompt_id => integer() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutRoutingsForward do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :destinations,
      :list,
      PlacetelAPI.Model.PutRoutingsForwardDestinationsInner,
      options
    )
  end
end
