# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutContacts do
  @moduledoc """
  Update a contact
  """

  @derive [Poison.Encoder]
  defstruct [
    :speeddial,
    :first_name,
    :last_name,
    :email,
    :email_work,
    :company,
    :address,
    :address_work,
    :phone_work,
    :mobile_work,
    :phone,
    :mobile,
    :fax,
    :fax_work,
    :facebook_url,
    :linkedin_url,
    :xing_url,
    :twitter_account,
    :color,
    :user_id,
    :blocked
  ]

  @type t :: %__MODULE__{
          :speeddial => String.t() | nil,
          :first_name => String.t() | nil,
          :last_name => String.t() | nil,
          :email => String.t() | nil,
          :email_work => String.t() | nil,
          :company => String.t() | nil,
          :address => String.t() | nil,
          :address_work => String.t() | nil,
          :phone_work => String.t() | nil,
          :mobile_work => String.t() | nil,
          :phone => String.t() | nil,
          :mobile => String.t() | nil,
          :fax => String.t() | nil,
          :fax_work => String.t() | nil,
          :facebook_url => String.t() | nil,
          :linkedin_url => String.t() | nil,
          :xing_url => String.t() | nil,
          :twitter_account => String.t() | nil,
          :color => String.t() | nil,
          :user_id => integer() | nil,
          :blocked => boolean() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutContacts do
  def decode(value, _options) do
    value
  end
end
