# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutGroups do
  @moduledoc """
  Update a group
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :description,
    :member_ids
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :description => String.t() | nil,
          :member_ids => [integer()] | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutGroups do
  def decode(value, _options) do
    value
  end
end
