# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.PutUsers do
  @moduledoc """
  Update a subuser
  """

  @derive [Poison.Encoder]
  defstruct [
    :first_name,
    :last_name,
    :email,
    :did,
    :callerid,
    :primary_sip_user_id,
    :admin_user,
    :rights_numbers,
    :locale,
    :obfuscate_billing_records,
    :obfuscate_others,
    :permissions,
    :avatar
  ]

  @type t :: %__MODULE__{
          :first_name => String.t() | nil,
          :last_name => String.t() | nil,
          :email => String.t() | nil,
          :did => integer() | nil,
          :callerid => String.t() | nil,
          :primary_sip_user_id => integer() | nil,
          :admin_user => boolean() | nil,
          :rights_numbers => [String.t()] | nil,
          :locale => String.t() | nil,
          :obfuscate_billing_records => boolean() | nil,
          :obfuscate_others => boolean() | nil,
          :permissions => PlacetelAPI.Model.PutUsersPermissions.t() | nil,
          :avatar => String.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.PutUsers do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:permissions, :struct, PlacetelAPI.Model.PutUsersPermissions, options)
  end
end
