# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Recording do
  @moduledoc """
  Recording model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :transcript,
    :direction,
    :from,
    :to,
    :duration,
    :time,
    :file,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :transcript => String.t() | nil,
          :direction => String.t() | nil,
          :from => String.t() | nil,
          :to => String.t() | nil,
          :duration => integer() | nil,
          :time => DateTime.t() | nil,
          :file => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Recording do
  def decode(value, _options) do
    value
  end
end
