# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.RoutingPlan do
  @moduledoc """
  RoutingPlan model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :description,
    :did,
    :routing_object_counts,
    :rings_for,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :did => integer() | nil,
          :routing_object_counts => String.t() | nil,
          :rings_for => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.RoutingPlan do
  def decode(value, _options) do
    value
  end
end
