# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.RoutingObject do
  @moduledoc """
  RoutingObject model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :forward,
    :group,
    :plan,
    :ivr,
    :queue,
    :api,
    :mailbox,
    :notification,
    :time_settings,
    :custom_caller_id,
    :notify_external_api,
    :music_on_hold,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :forward => PlacetelAPI.Model.RoutingObjectForward.t() | nil,
          :group => PlacetelAPI.Model.RoutingObjectGroup.t() | nil,
          :plan => PlacetelAPI.Model.RoutingObjectPlan.t() | nil,
          :ivr => PlacetelAPI.Model.RoutingObjectIvr.t() | nil,
          :queue => PlacetelAPI.Model.CallCenterQueue.t() | nil,
          :api => PlacetelAPI.Model.RoutingObjectApi.t() | nil,
          :mailbox => PlacetelAPI.Model.RoutingObjectMailbox.t() | nil,
          :notification => PlacetelAPI.Model.RoutingObjectNotification.t() | nil,
          :time_settings => PlacetelAPI.Model.RoutingObjectTimeSettings.t() | nil,
          :custom_caller_id => PlacetelAPI.Model.RoutingObjectCustomCallerId.t() | nil,
          :notify_external_api => String.t() | nil,
          :music_on_hold => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.RoutingObject do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:forward, :struct, PlacetelAPI.Model.RoutingObjectForward, options)
    |> deserialize(:group, :struct, PlacetelAPI.Model.RoutingObjectGroup, options)
    |> deserialize(:plan, :struct, PlacetelAPI.Model.RoutingObjectPlan, options)
    |> deserialize(:ivr, :struct, PlacetelAPI.Model.RoutingObjectIvr, options)
    |> deserialize(:queue, :struct, PlacetelAPI.Model.CallCenterQueue, options)
    |> deserialize(:api, :struct, PlacetelAPI.Model.RoutingObjectApi, options)
    |> deserialize(:mailbox, :struct, PlacetelAPI.Model.RoutingObjectMailbox, options)
    |> deserialize(:notification, :struct, PlacetelAPI.Model.RoutingObjectNotification, options)
    |> deserialize(:time_settings, :struct, PlacetelAPI.Model.RoutingObjectTimeSettings, options)
    |> deserialize(
      :custom_caller_id,
      :struct,
      PlacetelAPI.Model.RoutingObjectCustomCallerId,
      options
    )
  end
end
