# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.RoutingObjectPlan do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :destinations
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :destinations => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.RoutingObjectPlan do
  def decode(value, _options) do
    value
  end
end
