# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.RoutingObjectApi do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :max_retries,
    :backup_routing_plan_id,
    :prompt
  ]

  @type t :: %__MODULE__{
          :max_retries => String.t() | nil,
          :backup_routing_plan_id => String.t() | nil,
          :prompt => PlacetelAPI.Model.Prompt.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.RoutingObjectApi do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:prompt, :struct, PlacetelAPI.Model.Prompt, options)
  end
end
