# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.RoutingObjectForward do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :behaviour,
    :prompt_id,
    :destinations
  ]

  @type t :: %__MODULE__{
          :behaviour => String.t() | nil,
          :prompt_id => integer() | nil,
          :destinations => [PlacetelAPI.Model.Destination.t()] | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.RoutingObjectForward do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:destinations, :list, PlacetelAPI.Model.Destination, options)
  end
end
