# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.RoutingObjectIvr do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :prompt,
    :items,
    :catchall_routing_object
  ]

  @type t :: %__MODULE__{
          :prompt => PlacetelAPI.Model.Prompt.t() | nil,
          :items => String.t() | nil,
          :catchall_routing_object => PlacetelAPI.Model.RoutingObject.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.RoutingObjectIvr do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:prompt, :struct, PlacetelAPI.Model.Prompt, options)
    |> deserialize(:catchall_routing_object, :struct, PlacetelAPI.Model.RoutingObject, options)
  end
end
