# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.RoutingObjectGroup do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :group_ringing_time,
    :backup_behaviour,
    :backup_routing_object
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :group_ringing_time => String.t() | nil,
          :backup_behaviour => String.t() | nil,
          :backup_routing_object => PlacetelAPI.Model.RoutingObject.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.RoutingObjectGroup do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:backup_routing_object, :struct, PlacetelAPI.Model.RoutingObject, options)
  end
end
