# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.Subscription do
  @moduledoc """
  Subscription model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :url,
    :incoming,
    :outgoing,
    :hungup,
    :accepted,
    :phone,
    :numbers
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :url => String.t() | nil,
          :incoming => boolean() | nil,
          :outgoing => boolean() | nil,
          :hungup => boolean() | nil,
          :accepted => boolean() | nil,
          :phone => boolean() | nil,
          :numbers => [String.t()] | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.Subscription do
  def decode(value, _options) do
    value
  end
end
