# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule PlacetelAPI.Model.User do
  @moduledoc """
  User model
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :login,
    :email,
    :first_name,
    :last_name,
    :type,
    :did,
    :callerid,
    :primary_sip_user_id,
    :locale,
    :obfuscate_billing_records,
    :obfuscate_others,
    :admin_user,
    :rights_numbers,
    :permissions,
    :updated_at,
    :created_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :login => String.t() | nil,
          :email => String.t() | nil,
          :first_name => String.t() | nil,
          :last_name => String.t() | nil,
          :type => String.t() | nil,
          :did => integer() | nil,
          :callerid => String.t() | nil,
          :primary_sip_user_id => integer() | nil,
          :locale => String.t() | nil,
          :obfuscate_billing_records => boolean() | nil,
          :obfuscate_others => boolean() | nil,
          :admin_user => boolean() | nil,
          :rights_numbers => [String.t()] | nil,
          :permissions => PlacetelAPI.Model.Permission.t() | nil,
          :updated_at => DateTime.t() | nil,
          :created_at => DateTime.t() | nil
        }
end

defimpl Poison.Decoder, for: PlacetelAPI.Model.User do
  import PlacetelAPI.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:permissions, :struct, PlacetelAPI.Model.Permission, options)
  end
end
